image: docker:stable


stages:
  - publish


docker image:
  stage: publish
  only:
    - master
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:$(cat ./VERSION)" --rm ./
    - docker push "$CI_REGISTRY_IMAGE:$(cat ./VERSION)"
