image: docker:stable


stages:
  - publish


Docker Image:
  stage: publish
  only:
    - master
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:$(cat ./VERSION)" --build-arg PYTHON_VERSION=3.8-alpine --rm ./
    - docker push "$CI_REGISTRY_IMAGE"
